services:
  node1:
    build: .
    container_name: sna-node1
    environment:
      NODE_ID: node1
      RAFT_GRPC_ADDR: :9001
      RAFT_HTTP_ADDR: :8001
      RAFT_DATA_DIR: /data
      RAFT_PEERS: node1=node1:9001,node2=node2:9001,node3=node3:9001,node4=node4:9001,node5=node5:9001
    ports:
      - "9001:9001"
      - "8001:8001"
    volumes:
      - ./data/node1:/data
    networks: [raft]

  node2:
    build: .
    container_name: sna-node2
    environment:
      NODE_ID: node2
      RAFT_GRPC_ADDR: :9001
      RAFT_HTTP_ADDR: :8001
      RAFT_DATA_DIR: /data
      RAFT_PEERS: node1=node1:9001,node2=node2:9001,node3=node3:9001,node4=node4:9001,node5=node5:9001
    ports:
      - "9002:9001"
      - "8002:8001"
    volumes:
      - ./data/node2:/data
    networks: [raft]

  node3:
    build: .
    container_name: sna-node3
    environment:
      NODE_ID: node3
      RAFT_GRPC_ADDR: :9001
      RAFT_HTTP_ADDR: :8001
      RAFT_DATA_DIR: /data
      RAFT_PEERS: node1=node1:9001,node2=node2:9001,node3=node3:9001,node4=node4:9001,node5=node5:9001
    ports:
      - "9003:9001"
      - "8003:8001"
    volumes:
      - ./data/node3:/data
    networks: [raft]

  node4:
    build: .
    container_name: sna-node4
    environment:
      NODE_ID: node4
      RAFT_GRPC_ADDR: :9001
      RAFT_HTTP_ADDR: :8001
      RAFT_DATA_DIR: /data
      RAFT_PEERS: node1=node1:9001,node2=node2:9001,node3=node3:9001,node4=node4:9001,node5=node5:9001
    ports:
      - "9004:9001"
      - "8004:8001"
    volumes:
      - ./data/node4:/data
    networks: [raft]

  node5:
    build: .
    container_name: sna-node5
    environment:
      NODE_ID: node5
      RAFT_GRPC_ADDR: :9001
      RAFT_HTTP_ADDR: :8001
      RAFT_DATA_DIR: /data
      RAFT_PEERS: node1=node1:9001,node2=node2:9001,node3=node3:9001,node4=node4:9001,node5=node5:9001
    ports:
      - "9005:9001"
      - "8005:8001"
    volumes:
      - ./data/node5:/data
    networks: [raft]

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: sna-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [raft]

  loki:
    image: grafana/loki:3.1.0
    container_name: sna-loki
    command: -config.file=/etc/loki/local-config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./deployments/loki/local-config.yml:/etc/loki/local-config.yml:ro
    networks: [raft]

  promtail:
    image: grafana/promtail:3.1.0
    container_name: sna-promtail
    command: -config.file=/etc/promtail/config.yml
    user: root
    volumes:
      - ./deployments/promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [raft]

  grafana:
    image: grafana/grafana:11.1.0
    container_name: sna-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer

    # SMTP для Gmail
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: smtp.gmail.com:587
      GF_SMTP_USER: rishatshayhut@gmail.com
      GF_SMTP_PASSWORD: password # <-- replace with your email password 
      GF_SMTP_FROM_ADDRESS: rishatshayhut@gmail.com
      GF_SMTP_SKIP_VERIFY: "false"

    volumes:
      - ./deployments/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./deployments/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks: [raft]

networks:
  raft:
    driver: bridge
